import img1 from "../src/assets/Airbnb _ Holiday rentals_ cabins_ beach houses _ more/1.jpeg";
import img2 from "../src/assets/Airbnb _ Holiday rentals_ cabins_ beach houses _ more/2.jpeg";
import img3 from "../src/assets/Airbnb _ Holiday rentals_ cabins_ beach houses _ more/3.jpeg";
import img4 from "../src/assets/Airbnb _ Holiday rentals_ cabins_ beach houses _ more/4.jpg";
import img5 from "../src/assets/Airbnb _ Holiday rentals_ cabins_ beach houses _ more/5.jpeg";
import img6 from "../src/assets/Airbnb _ Holiday rentals_ cabins_ beach houses _ more/6.jpeg";
import img7 from "../src/assets/Airbnb _ Holiday rentals_ cabins_ beach houses _ more/7.jpeg";
import img8 from "../src/assets/Airbnb _ Holiday rentals_ cabins_ beach houses _ more/8.jpeg";
import img9 from "../src/assets/Airbnb _ Holiday rentals_ cabins_ beach houses _ more/9.jpeg";
import img10 from "../src/assets/Airbnb _ Holiday rentals_ cabins_ beach houses _ more/10.png";
import img11 from "../src/assets/Airbnb _ Holiday rentals_ cabins_ beach houses _ more/11.png";
import img12 from "../src/assets/Airbnb _ Holiday rentals_ cabins_ beach houses _ more/12.jpeg";
import img13 from "../src/assets/Airbnb _ Holiday rentals_ cabins_ beach houses _ more/13.jpeg";
import img14 from "../src/assets/Airbnb _ Holiday rentals_ cabins_ beach houses _ more/14.jpeg";
import img15 from "../src/assets/Airbnb _ Holiday rentals_ cabins_ beach houses _ more/15.jpeg";
import img16 from "../src/assets/Airbnb _ Holiday rentals_ cabins_ beach houses _ more/16.jpeg";
import img17 from "../src/assets/Airbnb _ Holiday rentals_ cabins_ beach houses _ more/17.jpeg";
import img18 from "../src/assets/Airbnb _ Holiday rentals_ cabins_ beach houses _ more/18.jpg";
import img19 from "../src/assets/Airbnb _ Holiday rentals_ cabins_ beach houses _ more/19.jpeg";
import img20 from "../src/assets/Airbnb _ Holiday rentals_ cabins_ beach houses _ more/20.jpeg";
const data = [
  {
    catogory: "icons",
    id: 1,
    image: {
      1: img1,
      2: img2,
      3: img3,
      4: img4,
    },
    title: "Haunt the beetlejuice House",
    description: "Hosted by Delia Deetz",
    status: "0$ per guest",
  },
  {
    catogory: "icons",
    id: 2,
    image: {
      1: img5,
      2: img6,
      3: img7,
      4: img8,
    },
    title: "Stay in Prince's Purple Rain House",
    description: "Hosted by Wendy and Lisa",
    status: "Sold out",
  },

  {
    catogory: "past experience",
    id: 1,
    image: {
      1: img1,
      2: img2,
      3: img3,
      4: img4,
    },
    title: "join the living room sesion with doja cat",
    description: "Hosted by doja cat",
    status: "Sold out",
  },
  {
    id: 2,
    image: {
      1: img5,
      2: img6,
      3: img7,
      4: img8,
    },
    title: "playdate at polly pocket's compact",
    description: "Hosted by polly pocket",
    status: "sold out",
    catogory: "past experience",
  },
  {
    id: 3,
    image: {
      1: img9,
      2: img10,
      3: img11,
      4: img12,
    },
    title: "go vip with kevin hart",
    description: "hosted by kevin hart",
    status: "sold out",
    catogory: "past experience",
  },
  {
    id: 4,
    image: {
      1: img13,
      2: img14,
      3: img15,
      4: img16,
    },
    title: "train at x-mansion",
    description: "hosted by jubilee",
    status: "sold out",
    catogory: "past experience",
  },
  {
    id: 5,
    image: {
      1: img17,
      2: img18,
      3: img19,
      4: img20,
    },
    title: "Live like Bollywood star Janhvi Kapoor",
    description: "Hosted by Janhvi Kapoor",
    status: "Sold out",
    catogory: "past experience",
  },
  {
    id: 6,
    image: {
      1: img1,
      2: img2,
      3: img3,
      4: img4,
    },
    title: "Open the Olympic Games at Musée d’Orsay",
    description: "Hosted by Mathieu Lehanneur",
    status: "Sold out",
    catogory: "past experience",
  },
  {
    id: 7,
    image: {
      1: img5,
      2: img6,
      3: img7,
      4: img8,
    },
    title: "Wake up in the Musée d’Orsay",
    description: "Hosted by Mathieu Lehanneur",
    status: "Sold out",
    catogory: "past experience",
  },
  {
    id: 8,
    image: {
      1: img9,
      2: img10,
      3: img11,
      4: img12,
    },
    title: "Make core memories with Inside Out 2",
    description: "Hosted by Joy",
    status: "Sold out",
    catogory: "past experience",
  },
  {
    id: 9,
    image: {
      1: img13,
      2: img14,
      3: img15,
      4: img16,
    },
    title: "Design your Incredibles Supersuit",
    description: "Hosted by Edna Mode",
    status: "Sold out",
    catogory: "past experience",
  },
  {
    id: 10,
    image: {
      1: img17,
      2: img18,
      3: img19,
      4: img20,
    },
    title: "Go on tour with Feid",
    description: "Hosted by Feid",
    status: "Sold out",
    catogory: "past experience",
  },
  {
    id: 11,
    image: {
      1: img1,
      2: img2,
      3: img3,
      4: img4,
    },
    title: "Game with Khaby Lame",
    description: "Hosted by Khaby Lame",
    status: "Sold out",
    catogory: "past experience",
  },
  {
    id: 12,
    image: {
      1: img5,
      2: img6,
      3: img7,
      4: img8,
    },
    title: "Crash at the X-Mansion",
    description: "Hosted by Jubilee",
    status: "Sold out",
    catogory: "past experience",
  },
  {
    id: 13,
    image: {
      1: img9,
      2: img10,
      3: img11,
      4: img12,
    },
    title: "Spend the night in the Ferrari Museum",
    description: "Hosted by Marc Gené",
    status: "Sold out",
    catogory: "past experience",
  },
  {
    id: 14,
    image: {
      1: img13,
      2: img14,
      3: img15,
      4: img16,
    },
    title: "Drift off in the Up house",
    description: "Hosted by Carl Fredricksen",
    status: "Sold out",
    catogory: "past experience",
  },
  {
    id: 15,
    image: {
      1: img17,
      2: img18,
      3: img19,
      4: img20,
    },
    title: "Shrek’s Swamp",
    description: "Hosted by Donkey",
    status: "Sold out",
    catogory: "past experience",
  },
  {
    id: 16,
    image: {
      1: img1,
      2: img2,
      3: img3,
      4: img4,
    },
    title: "Barbie’s Malibu DreamHouse, Ken’s Way",
    description: "Hosted by Ken",
    status: "Sold out",
    catogory: "past experience",
  },
  {
    id: 17,
    image: {
      1: img5,
      2: img6,
      3: img7,
      4: img8,
    },
    title: "Ted Lasso’s Favorite Pub",
    description: "Hosted by Mae",
    status: "Sold out",
    catogory: "past experience",
  },
  {
    id: 18,
    image: {
      1: img9,
      2: img10,
      3: img11,
      4: img12,
    },
    title: "Houseplant Retreat",
    description: "Hosted by Seth Rogen",
    status: "Sold out",
    catogory: "past experience",
  },
  {
    id: 19,
    image: {
      1: img13,
      2: img14,
      3: img15,
      4: img16,
    },
    title: "Home Alone Holiday",
    description: "Hosted by Buzz",
    status: "Sold out",
    catogory: "past experience",
  },
  {
    id: 20,
    image: {
      1: img17,
      2: img18,
      3: img19,
      4: img20,
    },
    title: "The Last Blockbuster",
    description: "Hosted by Sandi",
    status: "Sold out",
    catogory: "past experience",
  },
  {
    id: 21,
    image: {
      1: img1,
      2: img2,
      3: img3,
      4: img4,
    },
    title: "Sleepover at Polly Pocket’s Compact",
    description: "Hosted by Polly Pocket",
    status: "Sold out",
    catogory: "past experience",
  },

  {
    catogory: "omg",
    id: 1,
    catogory: "omg",
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    title: "Mumbai, India",
    description: "950 km away - 2-7 Nov",
    status: "₹12000 per night",
  },
  {
    id: 2,
    catogory: "omg",
    image: { 1: img5, 2: img6, 3: img7, 4: img8 },
    title: "Miami, America",
    description: "1100 km away - 5-10 Nov",
    status: "₹15000 per night",
  },
  {
    id: 3,
    catogory: "omg",
    image: { 1: img9, 2: img10, 3: img11, 4: img12 },
    title: "Paris, France",
    description: "1230 km away - 10-15 Nov",
    status: "₹13500 per night",
  },
  {
    id: 4,
    catogory: "omg",
    image: { 1: img13, 2: img14, 3: img15, 4: img16 },
    title: "Sydney, Australia",
    description: "1155 km away - 3-8 Nov",
    status: "₹14000 per night",
  },
  {
    id: 5,
    catogory: "omg",
    image: { 1: img17, 2: img18, 3: img19, 4: img20 },
    title: "Tokyo, Japan",
    description: "1040 km away - 12-17 Nov",
    status: "₹12500 per night",
  },
  {
    id: 6,
    catogory: "omg",
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    title: "Cairo, Egypt",
    description: "1085 km away - 7-12 Nov",
    status: "₹11800 per night",
  },
  {
    id: 7,
    catogory: "omg",
    image: { 1: img5, 2: img6, 3: img7, 4: img8 },
    title: "London, UK",
    description: "1210 km away - 8-13 Nov",
    status: "₹13000 per night",
  },
  {
    id: 8,
    catogory: "omg",
    image: { 1: img9, 2: img10, 3: img11, 4: img12 },
    title: "Dubai, UAE",
    description: "990 km away - 4-9 Nov",
    status: "₹14500 per night",
  },
  {
    id: 9,
    catogory: "omg",
    image: { 1: img13, 2: img14, 3: img15, 4: img16 },
    title: "Toronto, Canada",
    description: "1125 km away - 15-20 Nov",
    status: "₹13800 per night",
  },
  {
    id: 10,
    catogory: "omg",
    image: { 1: img17, 2: img18, 3: img19, 4: img20 },
    title: "New York, USA",
    description: "1205 km away - 1-6 Nov",
    status: "₹16000 per night",
  },
  {
    id: 11,
    catogory: "omg",
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    title: "Rome, Italy",
    description: "950 km away - 9-14 Nov",
    status: "₹11000 per night",
  },
  {
    id: 12,
    catogory: "omg",
    image: { 1: img5, 2: img6, 3: img7, 4: img8 },
    title: "Rio de Janeiro, Brazil",
    description: "1150 km away - 3-8 Nov",
    status: "₹15500 per night",
  },
  {
    id: 13,
    catogory: "omg",
    image: { 1: img9, 2: img10, 3: img11, 4: img12 },
    title: "Los Angeles, USA",
    description: "1235 km away - 5-10 Nov",
    status: "₹14200 per night",
  },
  {
    id: 14,
    catogory: "omg",
    image: { 1: img13, 2: img14, 3: img15, 4: img16 },
    title: "Bangkok, Thailand",
    description: "1020 km away - 6-11 Nov",
    status: "₹12500 per night",
  },
  {
    id: 15,
    catogory: "omg",
    image: { 1: img17, 2: img18, 3: img19, 4: img20 },
    title: "Moscow, Russia",
    description: "1108 km away - 7-12 Nov",
    status: "₹14000 per night",
  },
  {
    id: 16,
    catogory: "omg",
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    title: "Singapore",
    description: "1050 km away - 2-7 Nov",
    status: "₹12200 per night",
  },
  {
    id: 17,
    catogory: "omg",
    image: { 1: img5, 2: img6, 3: img7, 4: img8 },
    title: "Berlin, Germany",
    description: "1220 km away - 10-15 Nov",
    status: "₹13500 per night",
  },
  {
    id: 18,
    catogory: "omg",
    image: { 1: img9, 2: img10, 3: img11, 4: img12 },
    title: "Istanbul, Turkey",
    description: "1180 km away - 13-18 Nov",
    status: "₹14800 per night",
  },
  {
    id: 19,
    catogory: "omg",
    image: { 1: img13, 2: img14, 3: img15, 4: img16 },
    title: "Hong Kong, China",
    description: "1000 km away - 9-14 Nov",
    status: "₹13000 per night",
  },
  {
    id: 20,
    catogory: "omg",
    image: { 1: img17, 2: img18, 3: img19, 4: img20 },
    title: "Cape Town, South Africa",
    description: "1135 km away - 11-16 Nov",
    status: "₹12700 per night",
  },
  {
    id: 21,
    catogory: "omg",
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    title: "Lisbon, Portugal",
    description: "1057 km away - 14-19 Nov",
    status: "₹15000 per night",
  },
  {
    catogory: "historicalHomeData",
    id: 1,
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    title: "Colonial Mansion Stay",
    description: "200 km away - 1-6 Nov",
    status: "₹8000 per night",
  },
  {
    id: 2,
    catogory: "historicalHomeData",
    image: { 1: img5, 2: img6, 3: img7, 4: img8 },
    title: "Victorian Villa Retreat",
    description: "250 km away - 3-8 Nov",
    status: "₹9000 per night",
  },
  {
    id: 3,
    catogory: "historicalHomeData",
    image: { 1: img9, 2: img10, 3: img11, 4: img12 },
    title: "Heritage Homestead",
    description: "180 km away - 5-10 Nov",
    status: "₹7000 per night",
  },
  {
    id: 4,
    catogory: "historicalHomeData",
    image: { 1: img13, 2: img14, 3: img15, 4: img16 },
    title: "Ancient Castle Stay",
    description: "320 km away - 8-13 Nov",
    status: "₹12000 per night",
  },
  {
    id: 5,
    catogory: "historicalHomeData",
    image: { 1: img17, 2: img18, 3: img19, 4: img20 },
    title: "Renaissance Manor",
    description: "150 km away - 10-15 Nov",
    status: "₹8500 per night",
  },
  {
    id: 6,
    catogory: "historicalHomeData",
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    title: "Old Townhouse Experience",
    description: "400 km away - 6-11 Nov",
    status: "₹9500 per night",
  },
  {
    id: 7,
    catogory: "historicalHomeData",
    image: { 1: img5, 2: img6, 3: img7, 4: img8 },
    title: "Medieval Farmhouse Stay",
    description: "280 km away - 15-20 Nov",
    status: "₹10000 per night",
  },
  {
    id: 8,
    catogory: "historicalHomeData",
    image: { 1: img9, 2: img10, 3: img11, 4: img12 },
    title: "Tudor House Retreat",
    description: "220 km away - 2-7 Nov",
    status: "₹11000 per night",
  },
  {
    id: 9,
    catogory: "historicalHomeData",
    image: { 1: img13, 2: img14, 3: img15, 4: img16 },
    title: "Historic Lighthouse Stay",
    description: "300 km away - 12-17 Nov",
    status: "₹10500 per night",
  },
  {
    id: 10,
    catogory: "historicalHomeData",
    image: { 1: img17, 2: img18, 3: img19, 4: img20 },
    title: "Chateau Stay",
    description: "350 km away - 4-9 Nov",
    status: "₹13000 per night",
  },
  {
    id: 11,
    catogory: "historicalHomeData",
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    title: "Victorian Bed & Breakfast",
    description: "190 km away - 1-6 Nov",
    status: "₹7500 per night",
  },
  {
    id: 12,
    catogory: "historicalHomeData",
    image: { 1: img5, 2: img6, 3: img7, 4: img8 },
    title: "Plantation House Getaway",
    description: "400 km away - 10-15 Nov",
    status: "₹11500 per night",
  },
  {
    id: 13,
    catogory: "historicalHomeData",
    image: { 1: img9, 2: img10, 3: img11, 4: img12 },
    title: "Cottage from the Past",
    description: "260 km away - 8-13 Nov",
    status: "₹8200 per night",
  },
  {
    id: 14,
    catogory: "historicalHomeData",
    image: { 1: img13, 2: img14, 3: img15, 4: img16 },
    title: "Heritage Farmhouse",
    description: "230 km away - 3-8 Nov",
    status: "₹9500 per night",
  },
  {
    id: 15,
    catogory: "historicalHomeData",
    image: { 1: img17, 2: img18, 3: img19, 4: img20 },
    title: "Old Mill House",
    description: "270 km away - 6-11 Nov",
    status: "₹7800 per night",
  },
  {
    id: 16,
    catogory: "historicalHomeData",
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    title: "Historic Tavern Stay",
    description: "310 km away - 2-7 Nov",
    status: "₹8600 per night",
  },
  {
    id: 17,
    catogory: "historicalHomeData",
    image: { 1: img5, 2: img6, 3: img7, 4: img8 },
    title: "Old Stone House",
    description: "220 km away - 5-10 Nov",
    status: "₹9200 per night",
  },
  {
    id: 18,
    catogory: "historicalHomeData",
    image: { 1: img9, 2: img10, 3: img11, 4: img12 },
    title: "Colonial Farm Stay",
    description: "150 km away - 7-12 Nov",
    status: "₹8000 per night",
  },
  {
    id: 19,
    catogory: "historicalHomeData",
    image: { 1: img13, 2: img14, 3: img15, 4: img16 },
    title: "The Old Coach House",
    description: "240 km away - 12-17 Nov",
    status: "₹8300 per night",
  },
  {
    id: 20,
    catogory: "historicalHomeData",
    image: { 1: img17, 2: img18, 3: img19, 4: img20 },
    title: "Antique Home Stay",
    description: "300 km away - 9-14 Nov",
    status: "₹9100 per night",
  },
  {
    id: 21,
    catogory: "historicalHomeData",
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    title: "Restored Historical Lodge",
    description: "280 km away - 1-6 Nov",
    status: "₹8400 per night",
  },
  {
    catogory: "designHotelData",
    catogory: "designHotelData",
    id: 1,
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    title: "Minimalist Studio",
    description: "500 km away - 1-6 Nov",
    status: "₹7000 per night",
  },
  {
    catogory: "designHotelData",
    id: 2,
    image: { 1: img5, 2: img6, 3: img7, 4: img8 },
    title: "Modern Art Loft",
    description: "650 km away - 3-8 Nov",
    status: "₹8000 per night",
  },
  {
    catogory: "designHotelData",
    id: 3,
    image: { 1: img9, 2: img10, 3: img11, 4: img12 },
    title: "Eco-Friendly Cabin",
    description: "300 km away - 5-10 Nov",
    status: "₹6000 per night",
  },
  {
    catogory: "designHotelData",
    id: 4,
    image: { 1: img13, 2: img14, 3: img15, 4: img16 },
    title: "Vintage Chic Bungalow",
    description: "450 km away - 8-13 Nov",
    status: "₹7500 per night",
  },
  {
    catogory: "designHotelData",
    id: 5,
    image: { 1: img17, 2: img18, 3: img19, 4: img20 },
    title: "Art Deco Retreat",
    description: "800 km away - 10-15 Nov",
    status: "₹9000 per night",
  },
  {
    catogory: "designHotelData",
    id: 6,
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    title: "Contemporary Design House",
    description: "600 km away - 6-11 Nov",
    status: "₹8500 per night",
  },
  {
    catogory: "designHotelData",
    id: 7,
    image: { 1: img5, 2: img6, 3: img7, 4: img8 },
    title: "Bohemian Style Loft",
    description: "550 km away - 15-20 Nov",
    status: "₹7800 per night",
  },
  {
    catogory: "designHotelData",
    id: 8,
    image: { 1: img9, 2: img10, 3: img11, 4: img12 },
    title: "Industrial Chic Space",
    description: "700 km away - 2-7 Nov",
    status: "₹9200 per night",
  },
  {
    catogory: "designHotelData",
    id: 9,
    image: { 1: img13, 2: img14, 3: img15, 4: img16 },
    title: "Scandinavian Cabin",
    description: "400 km away - 12-17 Nov",
    status: "₹9500 per night",
  },
  {
    catogory: "designHotelData",
    id: 10,
    image: { 1: img17, 2: img18, 3: img19, 4: img20 },
    title: "Rustic Farmhouse Retreat",
    description: "500 km away - 4-9 Nov",
    status: "₹7200 per night",
  },
  {
    catogory: "designHotelData",
    id: 11,
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    title: "Geometric Design Loft",
    description: "330 km away - 1-6 Nov",
    status: "₹8800 per night",
  },
  {
    catogory: "designHotelData",
    id: 12,
    image: { 1: img5, 2: img6, 3: img7, 4: img8 },
    title: "Mid-Century Modern Retreat",
    description: "770 km away - 10-15 Nov",
    status: "₹8100 per night",
  },
  {
    catogory: "designHotelData",
    id: 13,
    image: { 1: img9, 2: img10, 3: img11, 4: img12 },
    title: "Contemporary Ocean View",
    description: "640 km away - 8-13 Nov",
    status: "₹9500 per night",
  },
  {
    catogory: "designHotelData",
    id: 14,
    image: { 1: img13, 2: img14, 3: img15, 4: img16 },
    title: "Cottage with Artistic Flair",
    description: "410 km away - 3-8 Nov",
    status: "₹7500 per night",
  },
  {
    catogory: "designHotelData",
    id: 15,
    image: { 1: img17, 2: img18, 3: img19, 4: img20 },
    title: "Stylish Penthouse Suite",
    description: "530 km away - 6-11 Nov",
    status: "₹9900 per night",
  },
  {
    catogory: "designHotelData",
    id: 16,
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    title: "Sleek Urban Apartment",
    description: "490 km away - 2-7 Nov",
    status: "₹8300 per night",
  },
  {
    catogory: "designHotelData",
    id: 17,
    image: { 1: img5, 2: img6, 3: img7, 4: img8 },
    title: "Creative Studio Space",
    description: "620 km away - 5-10 Nov",
    status: "₹7200 per night",
  },
  {
    catogory: "designHotelData",
    id: 18,
    image: { 1: img9, 2: img10, 3: img11, 4: img12 },
    title: "Exquisite Boutique Hotel",
    description: "480 km away - 7-12 Nov",
    status: "₹9500 per night",
  },
  {
    catogory: "designHotelData",
    id: 19,
    image: { 1: img13, 2: img14, 3: img15, 4: img16 },
    title: "Artistic Hideaway",
    description: "370 km away - 12-17 Nov",
    status: "₹7900 per night",
  },
  {
    catogory: "designHotelData",
    id: 20,
    image: { 1: img17, 2: img18, 3: img19, 4: img20 },
    title: "Design Haven",
    description: "260 km away - 9-14 Nov",
    status: "₹7200 per night",
  },
  {
    catogory: "designHotelData",
    id: 21,
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    title: "Innovative Living Space",
    description: "410 km away - 1-6 Nov",
    status: "₹8500 per night",
  },
  {
    catogory: "offTheGridHotelData",
    catogory: "offTheGridHotelData",
    id: 1,
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    title: "Remote Mountain Cabin",
    description: "300 km away - 1-6 Nov",
    status: "₹5000 per night",
  },
  {
    catogory: "offTheGridHotelData",
    id: 2,
    image: { 1: img5, 2: img6, 3: img7, 4: img8 },
    title: "Secluded Lakeside Lodge",
    description: "450 km away - 3-8 Nov",
    status: "₹6000 per night",
  },
  {
    catogory: "offTheGridHotelData",
    id: 3,
    image: { 1: img9, 2: img10, 3: img11, 4: img12 },
    title: "Forest Hideaway",
    description: "200 km away - 5-10 Nov",
    status: "₹5500 per night",
  },
  {
    catogory: "offTheGridHotelData",
    id: 4,
    image: { 1: img13, 2: img14, 3: img15, 4: img16 },
    title: "Desert Retreat",
    description: "600 km away - 8-13 Nov",
    status: "₹7000 per night",
  },
  {
    catogory: "offTheGridHotelData",
    id: 5,
    image: { 1: img17, 2: img18, 3: img19, 4: img20 },
    title: "Eco-Friendly Treehouse",
    description: "350 km away - 10-15 Nov",
    status: "₹6500 per night",
  },
  {
    catogory: "offTheGridHotelData",
    id: 6,
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    title: "Remote Beach Bungalow",
    description: "500 km away - 6-11 Nov",
    status: "₹6000 per night",
  },
  {
    catogory: "offTheGridHotelData",
    id: 7,
    image: { 1: img5, 2: img6, 3: img7, 4: img8 },
    title: "Island Escape",
    description: "800 km away - 15-20 Nov",
    status: "₹9000 per night",
  },
  {
    catogory: "offTheGridHotelData",
    id: 8,
    image: { 1: img9, 2: img10, 3: img11, 4: img12 },
    title: "Wilderness Yurt",
    description: "400 km away - 2-7 Nov",
    status: "₹5500 per night",
  },
  {
    catogory: "offTheGridHotelData",
    id: 9,
    image: { 1: img13, 2: img14, 3: img15, 4: img16 },
    title: "Mountain Climbing Cabin",
    description: "600 km away - 12-17 Nov",
    status: "₹7500 per night",
  },
  {
    catogory: "offTheGridHotelData",
    id: 10,
    image: { 1: img17, 2: img18, 3: img19, 4: img20 },
    title: "Off-Grid A-Frame",
    description: "700 km away - 4-9 Nov",
    status: "₹8000 per night",
  },
  {
    catogory: "offTheGridHotelData",
    id: 11,
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    title: "Hidden Cabin Retreat",
    description: "300 km away - 1-6 Nov",
    status: "₹5000 per night",
  },
  {
    catogory: "offTheGridHotelData",
    id: 12,
    image: { 1: img5, 2: img6, 3: img7, 4: img8 },
    title: "Bamboo Eco-Lodge",
    description: "400 km away - 10-15 Nov",
    status: "₹6000 per night",
  },
  {
    catogory: "offTheGridHotelData",
    id: 13,
    image: { 1: img9, 2: img10, 3: img11, 4: img12 },
    title: "Nature Retreat Cabin",
    description: "550 km away - 8-13 Nov",
    status: "₹6500 per night",
  },
  {
    catogory: "offTheGridHotelData",
    id: 14,
    image: { 1: img13, 2: img14, 3: img15, 4: img16 },
    title: "Cozy Forest Cabin",
    description: "250 km away - 3-8 Nov",
    status: "₹7000 per night",
  },
  {
    catogory: "offTheGridHotelData",
    id: 15,
    image: { 1: img17, 2: img18, 3: img19, 4: img20 },
    title: "Off-Grid Cottage",
    description: "300 km away - 6-11 Nov",
    status: "₹5500 per night",
  },
  {
    catogory: "offTheGridHotelData",
    id: 16,
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    title: "Hut in the Woods",
    description: "480 km away - 2-7 Nov",
    status: "₹6000 per night",
  },
  {
    catogory: "offTheGridHotelData",
    id: 17,
    image: { 1: img5, 2: img6, 3: img7, 4: img8 },
    title: "Mountain View Lodge",
    description: "520 km away - 5-10 Nov",
    status: "₹7000 per night",
  },
  {
    catogory: "offTheGridHotelData",
    id: 18,
    image: { 1: img9, 2: img10, 3: img11, 4: img12 },
    title: "Clifftop Cabin",
    description: "600 km away - 7-12 Nov",
    status: "₹8500 per night",
  },
  {
    catogory: "offTheGridHotelData",
    id: 19,
    image: { 1: img13, 2: img14, 3: img15, 4: img16 },
    title: "Cave House Retreat",
    description: "700 km away - 12-17 Nov",
    status: "₹9000 per night",
  },
  {
    catogory: "offTheGridHotelData",
    id: 20,
    image: { 1: img17, 2: img18, 3: img19, 4: img20 },
    title: "Treehouse Getaway",
    description: "350 km away - 9-14 Nov",
    status: "₹8000 per night",
  },
  {
    catogory: "offTheGridHotelData",
    id: 21,
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    title: "Off-Grid Glamping Tent",
    description: "400 km away - 1-6 Nov",
    status: "₹6500 per night",
  },
  {
    catogory: "lakeHotelData",
    catogory: "lakeHotelData",
    id: 1,
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    title: "Lakeside Cabin Retreat",
    description: "150 km away - 1-6 Nov",
    status: "₹5500 per night",
  },
  {
    catogory: "lakeHotelData",
    id: 2,
    image: { 1: img5, 2: img6, 3: img7, 4: img8 },
    title: "Charming Lake House",
    description: "200 km away - 3-8 Nov",
    status: "₹6000 per night",
  },
  {
    catogory: "lakeHotelData",
    id: 3,
    image: { 1: img9, 2: img10, 3: img11, 4: img12 },
    title: "Cozy Lakeside Bungalow",
    description: "250 km away - 5-10 Nov",
    status: "₹5000 per night",
  },
  {
    catogory: "lakeHotelData",
    id: 4,
    image: { 1: img13, 2: img14, 3: img15, 4: img16 },
    title: "Lakefront Cottage",
    description: "180 km away - 8-13 Nov",
    status: "₹7000 per night",
  },
  {
    catogory: "lakeHotelData",
    id: 5,
    image: { 1: img17, 2: img18, 3: img19, 4: img20 },
    title: "Luxury Lake Resort",
    description: "300 km away - 10-15 Nov",
    status: "₹9000 per night",
  },
  {
    catogory: "lakeHotelData",
    id: 6,
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    title: "Secluded Lakefront Cabin",
    description: "120 km away - 6-11 Nov",
    status: "₹6500 per night",
  },
  {
    catogory: "lakeHotelData",
    id: 7,
    image: { 1: img5, 2: img6, 3: img7, 4: img8 },
    title: "Rustic Lake Lodge",
    description: "220 km away - 15-20 Nov",
    status: "₹5800 per night",
  },
  {
    catogory: "lakeHotelData",
    id: 8,
    image: { 1: img9, 2: img10, 3: img11, 4: img12 },
    title: "Tranquil Lakeside Retreat",
    description: "300 km away - 2-7 Nov",
    status: "₹6200 per night",
  },
  {
    catogory: "lakeHotelData",
    id: 9,
    image: { 1: img13, 2: img14, 3: img15, 4: img16 },
    title: "Chalet by the Lake",
    description: "350 km away - 12-17 Nov",
    status: "₹8000 per night",
  },
  {
    catogory: "lakeHotelData",
    id: 10,
    image: { 1: img17, 2: img18, 3: img19, 4: img20 },
    title: "Modern Lakeside Villa",
    description: "400 km away - 4-9 Nov",
    status: "₹8500 per night",
  },
  {
    catogory: "lakeHotelData",
    id: 11,
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    title: "Charming Cottage on the Lake",
    description: "180 km away - 1-6 Nov",
    status: "₹5000 per night",
  },
  {
    catogory: "lakeHotelData",
    id: 12,
    image: { 1: img5, 2: img6, 3: img7, 4: img8 },
    title: "Breathtaking Lake View Lodge",
    description: "230 km away - 10-15 Nov",
    status: "₹7000 per night",
  },
  {
    catogory: "lakeHotelData",
    id: 13,
    image: { 1: img9, 2: img10, 3: img11, 4: img12 },
    title: "Rustic Lake Escape",
    description: "140 km away - 8-13 Nov",
    status: "₹5800 per night",
  },
  {
    catogory: "lakeHotelData",
    id: 14,
    image: { 1: img13, 2: img14, 3: img15, 4: img16 },
    title: "Family Lake House",
    description: "300 km away - 3-8 Nov",
    status: "₹6400 per night",
  },
  {
    catogory: "lakeHotelData",
    id: 15,
    image: { 1: img17, 2: img18, 3: img19, 4: img20 },
    title: "Scenic Lake Retreat",
    description: "260 km away - 6-11 Nov",
    status: "₹7500 per night",
  },
  {
    catogory: "lakeHotelData",
    id: 16,
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    title: "Peaceful Lake Cabin",
    description: "210 km away - 2-7 Nov",
    status: "₹5900 per night",
  },
  {
    catogory: "lakeHotelData",
    id: 17,
    image: { 1: img5, 2: img6, 3: img7, 4: img8 },
    title: "Lakeside Adventure Lodge",
    description: "300 km away - 5-10 Nov",
    status: "₹6700 per night",
  },
  {
    catogory: "lakeHotelData",
    id: 18,
    image: { 1: img9, 2: img10, 3: img11, 4: img12 },
    title: "Lakeside Camping Pod",
    description: "100 km away - 7-12 Nov",
    status: "₹4800 per night",
  },
  {
    catogory: "lakeHotelData",
    id: 19,
    image: { 1: img13, 2: img14, 3: img15, 4: img16 },
    title: "Lakehouse with Private Dock",
    description: "280 km away - 12-17 Nov",
    status: "₹7500 per night",
  },
  {
    catogory: "lakeHotelData",
    id: 20,
    image: { 1: img17, 2: img18, 3: img19, 4: img20 },
    title: "Luxury Cabin by the Lake",
    description: "350 km away - 9-14 Nov",
    status: "₹8500 per night",
  },
  {
    catogory: "lakeHotelData",
    id: 21,
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    title: "Romantic Lake Escape",
    description: "200 km away - 1-6 Nov",
    status: "₹6000 per night",
  },
  {
    catogory: "amazingViewHotelData",
    id: 1,
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    title: "Skyline View Apartment",
    description: "5 km away - 1-6 Nov",
    status: "₹7000 per night",
  },
  {
    catogory: "amazingViewHotelData",
    id: 2,
    image: { 1: img5, 2: img6, 3: img7, 4: img8 },
    title: "Mountain View Lodge",
    description: "50 km away - 3-8 Nov",
    status: "₹8000 per night",
  },
  {
    catogory: "amazingViewHotelData",
    id: 3,
    image: { 1: img9, 2: img10, 3: img11, 4: img12 },
    title: "Ocean View Villa",
    description: "30 km away - 5-10 Nov",
    status: "₹9000 per night",
  },
  {
    catogory: "amazingViewHotelData",
    id: 4,
    image: { 1: img13, 2: img14, 3: img15, 4: img16 },
    title: "Panoramic Cliff House",
    description: "100 km away - 8-13 Nov",
    status: "₹8500 per night",
  },
  {
    catogory: "amazingViewHotelData",
    id: 5,
    image: { 1: img17, 2: img18, 3: img19, 4: img20 },
    title: "Lakefront Luxury Cabin",
    description: "75 km away - 10-15 Nov",
    status: "₹9500 per night",
  },
  {
    catogory: "amazingViewHotelData",
    id: 6,
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    title: "Valley View Retreat",
    description: "40 km away - 6-11 Nov",
    status: "₹7000 per night",
  },
  {
    catogory: "amazingViewHotelData",
    id: 7,
    image: { 1: img5, 2: img6, 3: img7, 4: img8 },
    title: "Serenity Mountain Cabin",
    description: "25 km away - 15-20 Nov",
    status: "₹7800 per night",
  },
  {
    catogory: "amazingViewHotelData",
    id: 8,
    image: { 1: img9, 2: img10, 3: img11, 4: img12 },
    title: "Sunset View Lodge",
    description: "60 km away - 2-7 Nov",
    status: "₹8200 per night",
  },
  {
    catogory: "amazingViewHotelData",
    id: 9,
    image: { 1: img13, 2: img14, 3: img15, 4: img16 },
    title: "Oceanfront Bungalow",
    description: "80 km away - 12-17 Nov",
    status: "₹9000 per night",
  },
  {
    catogory: "amazingViewHotelData",
    id: 10,
    image: { 1: img17, 2: img18, 3: img19, 4: img20 },
    title: "Rooftop Penthouse",
    description: "10 km away - 4-9 Nov",
    status: "₹9500 per night",
  },
  {
    catogory: "amazingViewHotelData",
    id: 11,
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    title: "Forest View Cabin",
    description: "20 km away - 1-6 Nov",
    status: "₹6000 per night",
  },
  {
    catogory: "amazingViewHotelData",
    id: 12,
    image: { 1: img5, 2: img6, 3: img7, 4: img8 },
    title: "Desert Oasis with Views",
    description: "90 km away - 10-15 Nov",
    status: "₹7800 per night",
  },
  {
    catogory: "amazingViewHotelData",
    id: 13,
    image: { 1: img9, 2: img10, 3: img11, 4: img12 },
    title: "Majestic View Villa",
    description: "45 km away - 8-13 Nov",
    status: "₹8500 per night",
  },
  {
    catogory: "amazingViewHotelData",
    id: 14,
    image: { 1: img13, 2: img14, 3: img15, 4: img16 },
    title: "Highland View Lodge",
    description: "35 km away - 3-8 Nov",
    status: "₹7500 per night",
  },
  {
    catogory: "amazingViewHotelData",
    id: 15,
    image: { 1: img17, 2: img18, 3: img19, 4: img20 },
    title: "Scenic Lake Cabin",
    description: "70 km away - 6-11 Nov",
    status: "₹7000 per night",
  },
  {
    catogory: "amazingViewHotelData",
    id: 16,
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    catogory: "amazingViewHotelData",
    title: "Stunning Cliffside Retreat",
    description: "50 km away - 2-7 Nov",
    status: "₹8000 per night",
  },
  {
    catogory: "amazingViewHotelData",
    id: 17,
    image: { 1: img5, 2: img6, 3: img7, 4: img8 },
    title: "Waterfall View Lodge",
    description: "30 km away - 5-10 Nov",
    status: "₹9000 per night",
  },
  {
    catogory: "amazingViewHotelData",
    id: 18,
    image: { 1: img9, 2: img10, 3: img11, 4: img12 },
    title: "Skyline Cabin Retreat",
    description: "65 km away - 7-12 Nov",
    status: "₹8500 per night",
  },
  {
    catogory: "amazingViewHotelData",
    id: 19,
    image: { 1: img13, 2: img14, 3: img15, 4: img16 },
    catogory: "amazingViewHotelData",
    title: "Cliffside Bungalow",
    description: "120 km away - 12-17 Nov",
    status: "₹9500 per night",
  },
  {
    catogory: "amazingViewHotelData",
    id: 20,
    image: { 1: img17, 2: img18, 3: img19, 4: img20 },
    title: "Ocean View Paradise",
    description: "40 km away - 9-14 Nov",
    status: "₹8500 per night",
  },
  {
    catogory: "amazingViewHotelData",
    id: 21,
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    title: "Breathtaking Valley Cabin",
    description: "55 km away - 1-6 Nov",
    status: "₹7000 per night",
  },
  {
    catogory: "amazingPoolHotelData",
    catogory: "amazingPoolHotelData",
    id: 1,
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    title: "Infinity Pool Retreat",
    description: "15 km away - 1-6 Nov",
    status: "₹7000 per night",
  },
  {
    catogory: "amazingPoolHotelData",
    id: 2,
    image: { 1: img5, 2: img6, 3: img7, 4: img8 },
    title: "Oceanview Pool Villa",
    description: "25 km away - 3-8 Nov",
    status: "₹9000 per night",
  },
  {
    catogory: "amazingPoolHotelData",
    id: 3,
    image: { 1: img9, 2: img10, 3: img11, 4: img12 },
    title: "Lagoon Pool Resort",
    description: "10 km away - 5-10 Nov",
    status: "₹8000 per night",
  },
  {
    catogory: "amazingPoolHotelData",
    id: 4,
    image: { 1: img13, 2: img14, 3: img15, 4: img16 },
    title: "Private Pool Getaway",
    description: "35 km away - 8-13 Nov",
    status: "₹9500 per night",
  },
  {
    catogory: "amazingPoolHotelData",
    id: 5,
    image: { 1: img17, 2: img18, 3: img19, 4: img20 },
    title: "Luxury Resort with Waterfall Pool",
    description: "20 km away - 10-15 Nov",
    status: "₹10000 per night",
  },
  {
    catogory: "amazingPoolHotelData",
    id: 6,
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    title: "Tropical Pool Oasis",
    description: "5 km away - 6-11 Nov",
    status: "₹7500 per night",
  },
  {
    catogory: "amazingPoolHotelData",
    id: 7,
    image: { 1: img5, 2: img6, 3: img7, 4: img8 },
    title: "Rooftop Pool Suite",
    description: "30 km away - 15-20 Nov",
    status: "₹8500 per night",
  },
  {
    catogory: "amazingPoolHotelData",
    id: 8,
    image: { 1: img9, 2: img10, 3: img11, 4: img12 },
    title: "Villa with Infinity Pool",
    description: "12 km away - 2-7 Nov",
    status: "₹9000 per night",
  },
  {
    catogory: "amazingPoolHotelData",
    id: 9,
    image: { 1: img13, 2: img14, 3: img15, 4: img16 },
    title: "Spa Resort with Heated Pool",
    description: "40 km away - 12-17 Nov",
    status: "₹9500 per night",
  },
  {
    catogory: "amazingPoolHotelData",
    id: 10,
    image: { 1: img17, 2: img18, 3: img19, 4: img20 },
    title: "Eco-Friendly Resort with Natural Pool",
    description: "45 km away - 4-9 Nov",
    status: "₹8000 per night",
  },
  {
    catogory: "amazingPoolHotelData",
    id: 11,
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    title: "Charming Bungalow with Private Pool",
    description: "28 km away - 1-6 Nov",
    status: "₹7000 per night",
  },
  {
    catogory: "amazingPoolHotelData",
    id: 12,
    image: { 1: img5, 2: img6, 3: img7, 4: img8 },
    title: "Mountain Resort with Infinity Pool",
    description: "65 km away - 10-15 Nov",
    status: "₹9500 per night",
  },
  {
    catogory: "amazingPoolHotelData",
    id: 13,
    image: { 1: img9, 2: img10, 3: img11, 4: img12 },
    title: "Stylish Urban Pool Retreat",
    description: "8 km away - 8-13 Nov",
    status: "₹7500 per night",
  },
  {
    catogory: "amazingPoolHotelData",
    id: 14,
    image: { 1: img13, 2: img14, 3: img15, 4: img16 },
    title: "Luxury Hotel with Rooftop Pool",
    description: "20 km away - 3-8 Nov",
    status: "₹8000 per night",
  },
  {
    catogory: "amazingPoolHotelData",
    id: 15,
    image: { 1: img17, 2: img18, 3: img19, 4: img20 },
    title: "Exotic Pool Villa",
    description: "15 km away - 6-11 Nov",
    status: "₹9000 per night",
  },
  {
    catogory: "amazingPoolHotelData",
    id: 16,
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    title: "Modern Poolside Retreat",
    description: "25 km away - 2-7 Nov",
    status: "₹8000 per night",
  },
  {
    catogory: "amazingPoolHotelData",
    id: 17,
    image: { 1: img5, 2: img6, 3: img7, 4: img8 },
    title: "Elegant Pool House",
    description: "35 km away - 5-10 Nov",
    status: "₹7500 per night",
  },
  {
    catogory: "amazingPoolHotelData",
    id: 18,
    image: { 1: img9, 2: img10, 3: img11, 4: img12 },
    title: "Secluded Pool Retreat",
    description: "50 km away - 7-12 Nov",
    status: "₹9500 per night",
  },
  {
    catogory: "amazingPoolHotelData",
    id: 19,
    image: { 1: img13, 2: img14, 3: img15, 4: img16 },
    title: "Beachfront Villa with Pool",
    description: "60 km away - 12-17 Nov",
    status: "₹10000 per night",
  },
  {
    catogory: "amazingPoolHotelData",
    id: 20,
    image: { 1: img17, 2: img18, 3: img19, 4: img20 },
    title: "Stylish Poolside Villa",
    description: "30 km away - 9-14 Nov",
    status: "₹9000 per night",
  },
  {
    catogory: "amazingPoolHotelData",
    id: 21,
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    title: "Chic Resort with Swim-Up Bar",
    description: "5 km away - 1-6 Nov",
    status: "₹8000 per night",
  },
  {
    catogory: "farmStayHotelData",
    id: 1,
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    title: "Countryside Farmhouse",
    description: "10 km away - 1-6 Nov",
    status: "₹5000 per night",
  },
  {
    catogory: "farmStayHotelData",
    id: 2,
    image: { 1: img5, 2: img6, 3: img7, 4: img8 },
    title: "Organic Farm Retreat",
    description: "15 km away - 3-8 Nov",
    status: "₹6000 per night",
  },
  {
    catogory: "farmStayHotelData",
    id: 3,
    image: { 1: img9, 2: img10, 3: img11, 4: img12 },
    title: "Rustic Barn Stay",
    description: "25 km away - 5-10 Nov",
    status: "₹5500 per night",
  },
  {
    catogory: "farmStayHotelData",
    id: 4,
    image: { 1: img13, 2: img14, 3: img15, 4: img16 },
    title: "Farmhouse with Animals",
    description: "20 km away - 8-13 Nov",
    status: "₹6500 per night",
  },
  {
    catogory: "farmStayHotelData",
    id: 5,
    image: { 1: img17, 2: img18, 3: img19, 4: img20 },
    title: "Heritage Farm Stay",
    description: "12 km away - 10-15 Nov",
    status: "₹7000 per night",
  },
  {
    catogory: "farmStayHotelData",
    id: 6,
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    title: "Eco-Farm Lodge",
    description: "30 km away - 6-11 Nov",
    status: "₹6000 per night",
  },
  {
    catogory: "farmStayHotelData",
    id: 7,
    image: { 1: img5, 2: img6, 3: img7, 4: img8 },
    title: "Family Farm Stay",
    description: "5 km away - 15-20 Nov",
    status: "₹5000 per night",
  },
  {
    catogory: "farmStayHotelData",
    id: 8,
    image: { 1: img9, 2: img10, 3: img11, 4: img12 },
    title: "Country Cottage on Farm",
    description: "40 km away - 2-7 Nov",
    status: "₹7500 per night",
  },
  {
    catogory: "farmStayHotelData",
    id: 9,
    image: { 1: img13, 2: img14, 3: img15, 4: img16 },
    title: "Farmhouse Retreat with Scenic Views",
    description: "35 km away - 12-17 Nov",
    status: "₹6500 per night",
  },
  {
    catogory: "farmStayHotelData",
    id: 10,
    image: { 1: img17, 2: img18, 3: img19, 4: img20 },
    title: "Working Farm Stay",
    description: "18 km away - 4-9 Nov",
    status: "₹5500 per night",
  },
  {
    catogory: "farmStayHotelData",
    id: 11,
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    title: "Farm Stay in Nature",
    description: "22 km away - 1-6 Nov",
    status: "₹6000 per night",
  },
  {
    catogory: "farmStayHotelData",
    id: 12,
    image: { 1: img5, 2: img6, 3: img7, 4: img8 },
    title: "Traditional Farmhouse Experience",
    description: "28 km away - 10-15 Nov",
    status: "₹7000 per night",
  },
  {
    catogory: "farmStayHotelData",
    id: 13,
    image: { 1: img9, 2: img10, 3: img11, 4: img12 },
    title: "Luxury Farm Villa",
    description: "50 km away - 8-13 Nov",
    status: "₹9000 per night",
  },
  {
    catogory: "farmStayHotelData",
    id: 14,
    image: { 1: img13, 2: img14, 3: img15, 4: img16 },
    title: "Organic Vineyard Stay",
    description: "60 km away - 3-8 Nov",
    status: "₹8000 per night",
  },
  {
    catogory: "farmStayHotelData",
    id: 15,
    image: { 1: img17, 2: img18, 3: img19, 4: img20 },
    title: "Farm Stay with Pool",
    description: "45 km away - 6-11 Nov",
    status: "₹7500 per night",
  },
  {
    catogory: "farmStayHotelData",
    id: 16,
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    title: "Pet-Friendly Farm Stay",
    description: "20 km away - 2-7 Nov",
    status: "₹6000 per night",
  },
  {
    catogory: "farmStayHotelData",
    id: 17,
    image: { 1: img5, 2: img6, 3: img7, 4: img8 },
    title: "Rustic Eco-Farm",
    description: "8 km away - 5-10 Nov",
    status: "₹5500 per night",
  },
  {
    catogory: "farmStayHotelData",
    id: 18,
    image: { 1: img9, 2: img10, 3: img11, 4: img12 },
    title: "Scenic Farmhouse Cabin",
    description: "15 km away - 7-12 Nov",
    status: "₹7000 per night",
  },
  {
    catogory: "farmStayHotelData",
    id: 19,
    image: { 1: img13, 2: img14, 3: img15, 4: img16 },
    title: "Historic Farmhouse",
    description: "30 km away - 12-17 Nov",
    status: "₹8000 per night",
  },
  {
    catogory: "farmStayHotelData",
    id: 20,
    image: { 1: img17, 2: img18, 3: img19, 4: img20 },
    title: "Farm Stay with Culinary Experience",
    description: "25 km away - 9-14 Nov",
    status: "₹7500 per night",
  },
  {
    catogory: "farmStayHotelData",
    id: 21,
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    title: "Quaint Cottage on Farm",
    description: "11 km away - 1-6 Nov",
    status: "₹6000 per night",
  },
  {
    catogory: "uniqueHotelData",
    catogory: "uniqueHotelData",
    id: 1,
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    title: "Treehouse Retreat",
    description: "5 km away - 1-6 Nov",
    status: "₹8000 per night",
  },
  {
    catogory: "uniqueHotelData",
    id: 2,
    image: { 1: img5, 2: img6, 3: img7, 4: img8 },
    title: "Cave Hotel Experience",
    description: "15 km away - 3-8 Nov",
    status: "₹9500 per night",
  },
  {
    catogory: "uniqueHotelData",
    id: 3,
    image: { 1: img9, 2: img10, 3: img11, 4: img12 },
    title: "Floating Lodge",
    description: "10 km away - 5-10 Nov",
    status: "₹12000 per night",
  },
  {
    catogory: "uniqueHotelData",
    id: 4,
    image: { 1: img13, 2: img14, 3: img15, 4: img16 },
    title: "Converted Lighthouse Stay",
    description: "25 km away - 8-13 Nov",
    status: "₹11000 per night",
  },
  {
    catogory: "uniqueHotelData",
    id: 5,
    image: { 1: img17, 2: img18, 3: img19, 4: img20 },
    title: "Igloo Hotel",
    description: "30 km away - 10-15 Nov",
    status: "₹10000 per night",
  },
  {
    catogory: "uniqueHotelData",
    id: 6,
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    title: "Yurt Experience",
    description: "8 km away - 6-11 Nov",
    status: "₹7500 per night",
  },
  {
    catogory: "uniqueHotelData",
    id: 7,
    image: { 1: img5, 2: img6, 3: img7, 4: img8 },
    title: "Safari Tent Lodge",
    description: "20 km away - 15-20 Nov",
    status: "₹8500 per night",
  },
  {
    catogory: "uniqueHotelData",
    id: 8,
    image: { 1: img9, 2: img10, 3: img11, 4: img12 },
    title: "Houseboat Stay",
    description: "12 km away - 2-7 Nov",
    status: "₹9500 per night",
  },
  {
    catogory: "uniqueHotelData",
    id: 9,
    image: { 1: img13, 2: img14, 3: img15, 4: img16 },
    title: "Stay in a Castle",
    description: "40 km away - 12-17 Nov",
    status: "₹15000 per night",
  },
  {
    catogory: "uniqueHotelData",
    id: 10,
    image: { 1: img17, 2: img18, 3: img19, 4: img20 },
    title: "Converted Train Car",
    description: "18 km away - 4-9 Nov",
    status: "₹7000 per night",
  },
  {
    catogory: "uniqueHotelData",
    id: 11,
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    title: "Bubble Tent Stay",
    description: "5 km away - 1-6 Nov",
    status: "₹9000 per night",
  },
  {
    catogory: "uniqueHotelData",
    id: 12,
    image: { 1: img5, 2: img6, 3: img7, 4: img8 },
    title: "Hobbit House",
    description: "50 km away - 10-15 Nov",
    status: "₹11000 per night",
  },
  {
    catogory: "uniqueHotelData",
    id: 13,
    image: { 1: img9, 2: img10, 3: img11, 4: img12 },
    title: "Penthouse Suite in a Historic Building",
    description: "30 km away - 8-13 Nov",
    status: "₹12000 per night",
  },
  {
    catogory: "uniqueHotelData",
    id: 14,
    image: { 1: img13, 2: img14, 3: img15, 4: img16 },
    title: "Airstream Trailer Stay",
    description: "22 km away - 3-8 Nov",
    status: "₹8000 per night",
  },
  {
    catogory: "uniqueHotelData",
    id: 15,
    image: { 1: img17, 2: img18, 3: img19, 4: img20 },
    title: "Glass Igloo Experience",
    description: "15 km away - 6-11 Nov",
    status: "₹13000 per night",
  },
  {
    catogory: "uniqueHotelData",
    id: 16,
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    title: "Unique Stay in a Windmill",
    description: "28 km away - 2-7 Nov",
    status: "₹9000 per night",
  },
  {
    catogory: "uniqueHotelData",
    id: 17,
    image: { 1: img5, 2: img6, 3: img7, 4: img8 },
    title: "Stay in a Former Monastery",
    description: "35 km away - 5-10 Nov",
    status: "₹9500 per night",
  },
  {
    catogory: "uniqueHotelData",
    id: 18,
    image: { 1: img9, 2: img10, 3: img11, 4: img12 },
    title: "Bamboo Hut Experience",
    description: "12 km away - 7-12 Nov",
    status: "₹6000 per night",
  },
  {
    catogory: "uniqueHotelData",
    id: 19,
    image: { 1: img13, 2: img14, 3: img15, 4: img16 },
    title: "Ship Cabin Stay",
    description: "40 km away - 12-17 Nov",
    status: "₹7000 per night",
  },
  {
    catogory: "uniqueHotelData",
    id: 20,
    image: { 1: img17, 2: img18, 3: img19, 4: img20 },
    title: "Underground Bunker Stay",
    description: "45 km away - 9-14 Nov",
    status: "₹8000 per night",
  },
  {
    catogory: "uniqueHotelData",
    id: 21,
    image: { 1: img1, 2: img2, 3: img3, 4: img4 },
    title: "Cottage in the Clouds",
    description: "11 km away - 1-6 Nov",
    status: "₹8500 per night",
  },
];
export { data };
